add/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^teacher/$', views.addteacher, name='addteacher'),
    url(r'^question/$', views.addquestion, name='addquestion'),
    url(r'^ta/$', views.addta, name='addta'),
    url(r'^course/$', views.addcourse, name='addcourse'),
    url(r'^teacher/success$', views.addteacherdone, name='addteacherdone'),
    url(r'^question/success$', views.addquestiondone, name='addquestiondone'),
    url(r'^ta/success$', views.addtadone, name='addtadone'),
    url(r'^course/success$', views.addcoursedone, name='addcoursedone'),

]

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

logout/urls.py
from django.conf.urls import url
from . import views

app_name = "logout"
urlpatterns = [
    url(r'^$', views.log_out, name='log_out'),
]

online_judge/urls.py
from django.conf.urls import url,include
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    ##url(r'^$', views.home, name='home'),
    url(r'^$', include('home.urls')),
    url(r'^add/',include('add.urls')),
    url(r'^practice/', include('practice.urls')),
    url(r'^contest/', include('contest.urls')),
    url(r'^assignment/', include('assignment.urls')),
    url(r'^signup/', include('signup.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^logout/', include('logout.urls', namespace='logout')),
    url(r'^compile/', include('compile.urls')),
    url(r'^submit/', include('submitprob.urls')),
    url(r'^admin/', admin.site.urls),
]

submitprob/urls.py
from django.conf.urls import url
from . import views

app_name = "submitprob"
urlpatterns = [
    url(r'^$', views.problem, name='problem'),
    url(r'^successful/$', views.success, name='success'),
]

home/models.py
from django.db import models

# Create your models here.

submitprob/models.py
from django.db import models
from django.db.models.signals import post_save
from django import forms

# Create your models here.


class Problem(models.Model):
    # other fields here

    # fields in form
    problem_name = models.CharField(max_length=200)
    problem_id = models.AutoField(primary_key=True)
    submissions = models.PositiveIntegerField(default=0)
    correct = models.PositiveIntegerField(default=0)
    wrong_answer = models.PositiveIntegerField(default=0)
    compile_error = models.PositiveIntegerField(default=0)
    runtime_error = models.PositiveIntegerField(default=0)
    points = models.PositiveIntegerField(default=100)

submitprob/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=200)
    file = forms.FileField()

home/views.py
from django.contrib.auth.models import User
from signup.models import UserProfile
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

def home(request,username=""):
	user=request.user
	#ob = User.objects.all().filter(username=user.username)
	#print(username)
	ob1 = UserProfile.objects.all().filter(user_default_info_id=user.id)
	if len(ob1)!=0:
		isteacher=ob1[0].isteacher
		ista=ob1[0].ista
	else:
		ista=0
		isteacher=0
	#print(isteacher)
	#print(ista)
	return render(request,'home/home.html',{'username': username,'isteacher':isteacher,'ista':ista})

submitprob/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .forms import UploadFileForm
from submitprob.models import Problem
import subprocess
def problem(request):
	form = UploadFileForm()
	return render(request, 'submitprob/submit_problem.html', {'form': form})

def success(request):
	problem_name=request.POST.get('title')
	ob=Problem(problem_name=problem_name)
	ob.save()
	ob=Problem.objects.all().filter(problem_name=problem_name)
	upload_file(request,ob)
	try:
		subprocess.call('tar -xf Questions/'+str(ob[0].problem_id)+'/code.tar.gz -C '+'Questions/'+str(ob[0].problem_id)+'/',shell=True)
	except:
		return HttpResponse("Format required: .tar.gz")	
	subprocess.call('rm -r Questions/'+str(ob[0].problem_id)+'/code.tar.gz',shell=True)
	loadproblem(request,ob[0].problem_name)
	
def loadproblem(request,title):
	ob=Problem.objects.all().filter(problem_name=title)
	try:
		file1=open('Questions/'+str(ob[0].problem_id)+'/'+problem_name+'.txt','r')
	except:
		return HttpResponse("No question exists")
	val=file1.read()
	file1.close()
	return render(request, 'submitprob/success.html',{'problem':ob[0],'value':val})

def handle_uploaded_file(f,ob):
	subprocess.call('mkdir Questions/'+str(ob[0].problem_id),shell=True)
	subprocess.call('mkdir Submissions/'+str(ob[0].problem_id),shell=True)
	with open('Questions/'+str(ob[0].problem_id)+'/code.tar.gz', 'wb+') as destination:
		for chunk in f.chunks():
			destination.write(chunk)

def upload_file(request,ob):
	if request.method == 'POST':
		form = UploadFileForm(request.POST, request.FILES)
		if form.is_valid():
			handle_uploaded_file(request.FILES['file'],ob)
			return HttpResponseRedirect('/success/url/')
	else:
		form = UploadFileForm()
	return render(request, 'upload.html', {'form': form})

home/templates/submitprob/submit_problem.html
<form action="{% url 'submitprob:success' %}" method="POST" enctype="multipart/form-data" >
	{% csrf_token %}
	{{form}}
	<br>
	<input type="submit" value="Submit">
</form>

home/templates/submitprob/success.html
<form action="/compile/submit" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="/static/css/submitprob/style.css" >


{% if user.username %}


<div id="menu">
	<img src="/static/images/judge.jpg" id="img1">
    <div id="logout">
        <a href="{% url 'logout:log_out' %}"> <button class="button"><span>logout</span></button> </a>
    </div>

    <div id="hi">
        Hi <a href="/profile/{{user.username}}">{{user.username}} </a>
    </div>

    <div id="line"></div>

	</div>

	<div id="content">
		<h1>{{problem.problem_name}}</h1>
		<pre>{{value}}</pre>


		{% if messages %}
		<div class="span12">
		{% for message in messages %}
    		<div class="alert alert-{{ message.tags }}">
        		{{ message|safe }}
    		</div>
		{% endfor %}
		</div>
		{% endif %}

		<br>

<input name="prob_name" value="{{problem.problem_name}}" readonly hidden> </input><br>
<input name="user_name" value="{{user.username}}" readonly hidden> </input><br>
		<select name="language">
			<option value="c">C</option>
			<option value="cpp">C++</option>
			<option value="java">Java</option>
			<option value="python">Python</option>
		</select>
		<br />
		<input type="file" name="file">
		<textarea id="code" type="text" maxlength="100000000000" name="code" cols="10" rows="5000000" style="width:200px; height:50px;"></textarea>
		<br />
		<input id="submit" value="submit" type="submit" >

		<br><br>
	</div>
</form>

{% endif %}

{% if not user.username %}

<div id="menu">
	<img src="/static/images/judge.jpg" id="img1">
    <div id="signup">
        <a href="/signup"> <button class="button"><span>signup</span></button></a>
    </div>

    <div id="login">
        <a href="/login"><button class="button"><span>login</span></button></a>

    </div>

    <div id="line"></div>
	</div>

    <div id="content"><p>Please login to view questions </p></div>


{% endif %}