add/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^teacher/$', views.addteacher, name='addteacher'),
    url(r'^question/$', views.addquestion, name='addquestion'),
    url(r'^ta/$', views.addta, name='addta'),
    url(r'^course/$', views.addcourse, name='addcourse'),
    url(r'^teacher/success$', views.addteacherdone, name='addteacherdone'),
    url(r'^question/success$', views.addquestiondone, name='addquestiondone'),
    url(r'^ta/success$', views.addtadone, name='addtadone'),
    url(r'^course/success$', views.addcoursedone, name='addcoursedone'),

]

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

login/urls.py
from django.conf.urls import url
from . import views

app_name = "login"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile/$', views.login_done, name='login_done'),
]

logout/urls.py
from django.conf.urls import url
from . import views

app_name = "logout"
urlpatterns = [
    url(r'^$', views.log_out, name='log_out'),
]

online_judge/urls.py
from django.conf.urls import url,include
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    ##url(r'^$', views.home, name='home'),
    url(r'^$', include('home.urls')),
    url(r'^add/',include('add.urls')),
    url(r'^practice/', include('practice.urls')),
    url(r'^contest/', include('contest.urls')),
    url(r'^assignment/', include('assignment.urls')),
    url(r'^signup/', include('signup.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^logout/', include('logout.urls', namespace='logout')),
    url(r'^compile/', include('compile.urls')),
    url(r'^submit/', include('submitprob.urls')),
    url(r'^admin/', admin.site.urls),
]

home/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

home/views.py
from django.contrib.auth.models import User
from signup.models import UserProfile
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

def home(request,username=""):
	user=request.user
	#ob = User.objects.all().filter(username=user.username)
	#print(username)
	ob1 = UserProfile.objects.all().filter(user_default_info_id=user.id)
	if len(ob1)!=0:
		isteacher=ob1[0].isteacher
		ista=ob1[0].ista
	else:
		ista=0
		isteacher=0
	#print(isteacher)
	#print(ista)
	return render(request,'home/home.html',{'username': username,'isteacher':isteacher,'ista':ista})

login/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.models import User
from signup.models import UserProfile
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login
from django.contrib import messages


def index(request):
	return render(request,'login/index.html')


def login_done(request):
	username = request.POST.get("username")
	password = request.POST.get("password")
	user=authenticate(username=username, password=password)
	if user is not None:
		login(request, user)
		return HttpResponseRedirect("/",{'username': username})
	elif len(username)==0 or len(password)==0:
		messages.error(request, 'username and password cannot be empty')
		return HttpResponseRedirect('/login/')
	else:
		messages.error(request, 'username and password do not match')
		return HttpResponseRedirect('/login/')


'''if len(ob1)==0:
	return HttpResponseRedirect(reverse('login:index'), {'error_message': "Invalid Username"})
	else:
		ob2 = ob1[0].check_password(password)
		if not ob2:
			return HttpResponseRedirect(reverse('login:index'), {'error_message': "Invalid Username"})
	context = {'username':username}
	return render(request,'login/login_done.html',context)'''

	

home/templates/login/index.html
<link rel="stylesheet" type="text/css" href="/static/css/login/style.css">

{% if user.username %}
<div id="menu">
    <img src="/static/images/judge.jpg" id="img1">
    <div id="logout">
        <a href="{% url 'logout:log_out' %}"> <button class="button"><span>logout</span></button> </a>
    </div>

    <div id="hi">
        Hi <a href="/profile/{{user.username}}">{{user.username}} </a>
    </div>

    <div id="line"></div>
    </div>

    <div class="wrapper1" id="wrapper1">


        <div id="content1">
            <div class="content2">

            <br><hr>
                <br>You are already logged in<br>
                <br>Please logout to login from a different account<br>
                </div>
        </div>


        <hr>
        <div id="footer"></div>



    </div>

{% endif %}

{% if not user.username %}

<div id="menu">
    <img src="/static/images/judge.jpg" id="img1">
    <div id="signup">
        <a href="/signup"> <button class="button"><span>signup</span></button></a>
    </div>

    <div id="line"></div>
    </div>

<div class="wrapper1" id="wrapper1">


        <div id="content1">
            <div class="content2">
            <br>Welcome ! Please login to continue
            <br><br><hr>
            {% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
            {% if messages %}
            <div class="span12">
            {% for message in messages %}
                 <div class="alert alert-{{ message.tags }}">
                    <b>* {{ message|safe }}</b>
                    </div>
            {% endfor %}
            </div>
            {% endif %}

            <form action="{% url 'login:login_done' %}" method="POST" >
            {% csrf_token %}
            <br>

            <div class="label"><label>Username :   </label></div><div class="input"><input type="text" name="username" id="username"></div><br>
            <br><div class="label"><label>Password :   </label></div><div class="input"><input type="password" name="password"></div><br>

            <br><br><input type="submit" value="Submit">
        </form><br>

                <div class="er"><b>* Please sign up if you do not have an account</b></div>
                </div>
        </div>


        <hr>
        <div id="footer">


        </div>



    </div>

{% endif %}

home/templates/login/login_done.html
<h1> Welcome {{username}} !! </h1>