add/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^teacher/$', views.addteacher, name='addteacher'),
    url(r'^question/$', views.addquestion, name='addquestion'),
    url(r'^ta/$', views.addta, name='addta'),
    url(r'^course/$', views.addcourse, name='addcourse'),
    url(r'^teacher/success$', views.addteacherdone, name='addteacherdone'),
    url(r'^question/success$', views.addquestiondone, name='addquestiondone'),
    url(r'^ta/success$', views.addtadone, name='addtadone'),
    url(r'^course/success$', views.addcoursedone, name='addcoursedone'),

]

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

logout/urls.py
from django.conf.urls import url
from . import views

app_name = "logout"
urlpatterns = [
    url(r'^$', views.log_out, name='log_out'),
]

online_judge/urls.py
from django.conf.urls import url,include
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    ##url(r'^$', views.home, name='home'),
    url(r'^$', include('home.urls')),
    url(r'^add/',include('add.urls')),
    url(r'^practice/', include('practice.urls')),
    url(r'^contest/', include('contest.urls')),
    url(r'^assignment/', include('assignment.urls')),
    url(r'^signup/', include('signup.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^logout/', include('logout.urls', namespace='logout')),
    url(r'^compile/', include('compile.urls')),
    url(r'^submit/', include('submitprob.urls')),
    url(r'^admin/', admin.site.urls),
]

signup/urls.py
from django.conf.urls import url
from . import views

app_name = "signup"
urlpatterns = [
    url(r'^$', views.form, name='form'),
    url(r'^successful_sign_up/$', views.signup_done, name='signup_done'),
]

home/models.py
from django.db import models

# Create your models here.

signup/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django import forms

# Create your models here.


class UserProfile(models.Model):
    user_default_info = models.OneToOneField(User)
    # other fields here

    # fields in form
    middle_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10)
    dob = models.CharField(max_length=50)
    institute = models.CharField(max_length=200)
    year_joined_institute = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=50)
    tshirt_size = models.CharField(max_length=3)
    contact_number = models.CharField(max_length=12)
    isteacher=models.BooleanField(default=False)
    ista=models.BooleanField(default=False)
    isstudent=models.BooleanField(default=True)

    # fields to be updated automatically after submission
    submissions = models.PositiveIntegerField(default=0)
    correct = models.PositiveIntegerField(default=0)
    wrong_answer = models.PositiveIntegerField(default=0)
    compile_error = models.PositiveIntegerField(default=0)
    runtime_error = models.PositiveIntegerField(default=0)
    points = models.PositiveIntegerField(default=0)
    rank = models.PositiveIntegerField(default=0)
    institute_rank = models.PositiveIntegerField(default=0)

class Courses(models.Model):
    course_name=models.CharField(max_length=100)
    students=models.ManyToManyField(UserProfile,related_name="students")
    tas=models.ManyToManyField(UserProfile,related_name="tas")
    teachers=models.ManyToManyField(UserProfile,related_name="teachers")

home/views.py
from django.contrib.auth.models import User
from signup.models import UserProfile
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

def home(request,username=""):
	user=request.user
	#ob = User.objects.all().filter(username=user.username)
	#print(username)
	ob1 = UserProfile.objects.all().filter(user_default_info_id=user.id)
	if len(ob1)!=0:
		isteacher=ob1[0].isteacher
		ista=ob1[0].ista
	else:
		ista=0
		isteacher=0
	#print(isteacher)
	#print(ista)
	return render(request,'home/home.html',{'username': username,'isteacher':isteacher,'ista':ista})

signup/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from datetime import datetime
from .models import UserProfile
from django.template import loader
from django.contrib import messages
from django.core.mail import send_mail



# Create your views here.

def form(request):
    return render(request,'signup/form.html')


def signup_done(request):
    username=request.POST.get('username')
    first_name=request.POST.get('first_name')
    middle_name=request.POST.get('middle_name')
    last_name=request.POST.get('last_name')
    gender=request.POST.get('gender')
    dob=request.POST.get('dob')
    email=request.POST.get('email')
    contact_number=request.POST.get('contact_number')
    institute=request.POST.get('institute')
    year_joined_institute=request.POST.get('year_joined_institute')
    city=request.POST.get('city')
    country=request.POST.get('country')
    tshirt_size=request.POST.get('tshirt_size')

    if (len(username) == 0):
        messages.error(request, 'username cannot be empty')
        return HttpResponseRedirect('/signup/')


    try:
        dob_object = datetime.strptime(dob,'%d/%m/%Y')
    except:
        messages.error(request, 'Input Date Of Birth in format dd/mm/yyyy')
        return HttpResponseRedirect('/signup/')

    ob4 = User.objects.all().filter(username=username)
    if len(ob4) != 0:
        messages.error(request, 'username already exists')
        return HttpResponseRedirect('/signup/')


    ob = User(username=username,
              first_name=first_name,
              last_name=last_name,
              email=email,
              )
    ob.set_password('1234')
    ob.save()
    ob3 = User.objects.all().filter(username=username)

    ob2 = UserProfile(user_default_info=ob3[0],
                      middle_name=middle_name,
                      gender=gender,
                      dob=dob,
                      contact_number=contact_number,
                      institute=institute,
                      year_joined_institute=year_joined_institute,
                      city=city,
                      country=country,
                      tshirt_size=tshirt_size
                      )
    ob2.save()
    return HttpResponse('Signup successful and your password is 1234. Please log in to continue')

home/templates/signup/form.html
<link rel="stylesheet" type="text/css" href="/static/css/signup/style.css">

{% if user.username %}
<div id="menu">
    <img src="/static/images/judge.jpg" id="img1">
    <div id="logout">
        <a href="{% url 'logout:log_out' %}"> <button class="button"><span>logout</span></button> </a>
    </div>

    <div id="hi">
        Hi <a href="/profile/{{user.username}}">{{user.username}} </a>
    </div>

    <div id="line"></div>
    </div>

    <div class="wrapper1" id="wrapper1">


        <div id="content1">
            <div class="content2">

            <br><hr>
                <br>You are already logged in<br>

                </div>
        </div>


        <hr>
        <div id="footer"></div>



    </div>

{% endif %}

{% if not user.username %}


<div id="menu">
    <img src="/static/images/judge.jpg" id="img1">
    <div id="login">
        <a href="/login"><button class="button"><span>login</span></button></a>

    </div>

    <div id="line"></div>
    </div>

<div class="wrapper2" id="wrapper2">


        <div id="content3">
            <div class="content4">
            <br>Welcome ! Please sign up to continue<br>
            <br><hr>
            {% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
            {% if messages %}
            <div class="span12">
            {% for message in messages %}
                 <div class="alert alert-{{ message.tags }}">
                    <b>*{{ message|safe }}</b>
                    </div>
            {% endfor %}
            </div>
            {% endif %}

            <form action="{% url 'signup:signup_done' %}" method="POST" >
                {% csrf_token %}
                <br>
                    <div class="label"><label>Username : </label></div><div class="input"><input type="text" name="username"></div><br>
                    <br><div class="label"><label>First Name : </label></div><div class="input"><input type="text" name="first_name"></div><br>
                    <br><div class="label"><label>Middle Name : </label></div><div class="input"><input type="text" name="middle_name"></div><br>
                    <br><div class="label"><label>Last Name : </label></div><div class="input"><input type="text" name="last_name"></div><br>
                    <br><div class="label"><label>Gender : </label></div>
                    <div class="input"><select name="gender">
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select></div><br>
                    <br><div class="label"><label>Date of Birth : </label></div><div class="input"><input type="text" name="dob" data- /></div><br>
                    <br><div class="label"><label>Contact Number : </label></div><div class="input"><input type="text" name="contact_number"></div><br>
                    <br><div class="label"><label>Email : </label></div><div class="input"><input type="email" name="email"></div><br>
                    <br><div class="label"><label>Institute Name : </label></div><div class="input"><input type="text" name="institute"></div><br>
                    <br><div class="label"><label>Year of joining institute : </label></div><div class="input"><input type="text" name="year_joined_institute"></div><br>
                    <br><div class="label"><label>City : </label></div><div class="input"><input type="text" name="city"></div><br>
                    <br><div class="label"><label>Country : </label></div><div class="input"><input type="text" name="country"></div><br>
                    <br><div class="label"><label>T-Shirt Size : </label></div>
                    <div class="input"><select name="tshirt_size">
                        <option value="S">S</option>
                        <option value="M">M</option>
                        <option value="L">L</option>
                        <option value="XL">XL</option>
                        <option value="XXL">XXL</option>
                    </select></div><br>

                        <br><br><br><input type="submit" value="Submit">
            </form>

                <br><br><br><div class="er"><b>* Please login if you already have an account</b></div>
                </div>
        </div>


        <hr>
        <div id="footer">


        </div>



    </div>






{% endif %}